<script lang="ts">
  import '../app.css';
  import { auth } from '$lib/stores/auth.svelte';
  import { page } from '$app/stores';
  import Sidebar from '$lib/components/layout/Sidebar.svelte';
  import Header from '$lib/components/layout/Header.svelte';
  import BottomNav from '$lib/components/layout/BottomNav.svelte';
  // PWA web-manifest link (ADR-0007). pwaInfo carries the manifest filename
  // generated by vite-plugin-pwa (resolved against scope/base), so we inject its
  // <link> into <head> rather than hardcoding the path. The service worker
  // itself is auto-registered by the plugin (injectRegister: 'auto').
  import { pwaInfo } from 'virtual:pwa-info';

  let { children } = $props();

  const webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

  // Identity is established at the edge by Authentik forward-auth (ADR-0003);
  // there is no in-app login. We just resolve who the backend sees.
  $effect(() => {
    auth.checkAuth();
  });

  let pageTitle = $derived(() => {
    const path = $page.url.pathname;
    if (path === '/') return 'Dashboard';
    if (path.startsWith('/metrics')) return 'Metrics';
    if (path.startsWith('/workouts')) return 'Workouts';
    if (path.startsWith('/exercises')) return 'Exercises';
    if (path.startsWith('/sleep')) return 'Sleep';
    if (path.startsWith('/body')) return 'Body';
    if (path.startsWith('/trends')) return 'Trends';
    if (path.startsWith('/settings')) return 'Settings';
    return 'Health Dashboard';
  });
</script>

<svelte:head>
  <!-- Trusted, build-time plugin output (the manifest <link> tag) — not user input. -->
  {@html webManifestLink}
</svelte:head>

{#if auth.loading}
  <div class="flex items-center justify-center min-h-screen bg-surface-950">
    <div class="flex flex-col items-center gap-4">
      <div class="w-10 h-10 border-3 border-primary-500 border-t-transparent rounded-full animate-spin"></div>
      <p class="text-surface-400 text-sm">Loading...</p>
    </div>
  </div>
{:else if auth.user}
  <div class="flex h-screen overflow-hidden bg-surface-950">
    <!-- Desktop sidebar (hidden on phones; bottom bar is the mobile nav) -->
    <div class="hidden lg:block">
      <Sidebar />
    </div>

    <!-- Main content -->
    <div class="flex-1 flex flex-col overflow-hidden">
      <Header title={pageTitle()} />
      <!-- Bottom padding (pb-20) keeps content clear of the fixed mobile tab bar;
           reset on lg where the bar is hidden. -->
      <main class="flex-1 overflow-y-auto p-4 pb-20 lg:p-6 lg:pb-6">
        {@render children()}
      </main>
    </div>

    <!-- Phone-first primary navigation -->
    <BottomNav />
  </div>
{:else}
  <!-- Behind Authentik forward-auth this is unreachable; locally it means no
       identity header and no DEV_AUTH_EMAIL set. -->
  <div class="flex items-center justify-center min-h-screen bg-surface-950 px-4">
    <div class="text-center">
      <h1 class="text-xl font-semibold text-surface-100">Not signed in</h1>
      <p class="text-sm text-surface-500 mt-2">
        This app is protected by single sign-on. Sign in through your identity provider to continue.
      </p>
    </div>
  </div>
{/if}
