kind: pipeline
type: kubernetes
name: default

services:
  - name: test-db
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: health
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: apple_health_test

steps:
  - name: backend-lint
    image: python:3.12-slim
    commands:
      - pip install ruff
      - cd backend && ruff check . && ruff format --check .

  - name: backend-test
    image: python:3.12-slim
    environment:
      TEST_DATABASE_URL: postgresql+asyncpg://health:testpass@test-db:5432/apple_health_test
      DATABASE_URL: postgresql+asyncpg://health:testpass@test-db:5432/apple_health_test
      SECRET_KEY: test-secret-key
      TEST_MODE: "true"
    commands:
      - cd backend && pip install ".[dev]" && python -m pytest tests/ -v --tb=short
    depends_on:
      - backend-lint

  - name: frontend-check
    image: node:22-slim
    commands:
      - cd frontend && npm ci && npx svelte-check --fail-on-warnings && npm run build

  - name: build-and-push
    image: plugins/docker
    settings:
      repo: viktorbarzin/health
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
    depends_on:
      - backend-test
      - frontend-check

  - name: deploy
    image: curlimages/curl
    commands:
      - 'curl -s -X PATCH "https://kubernetes:6443/apis/apps/v1/namespaces/health/deployments/health" -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" -k -d ''[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"viktorbarzin/health:''"$DRONE_BUILD_NUMBER"''"}]'' | head'
    depends_on:
      - build-and-push

trigger:
  branch:
    - main
  event:
    - push
