kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: viktorbarzin/health
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}

  - name: deploy
    image: curlimages/curl
    commands:
      - |
        curl -sSk -X PATCH \
          -H "Authorization: Bearer $$KUBE_TOKEN" \
          -H "Content-Type: application/strategic-merge-patch+json" \
          --data '{"spec":{"template":{"metadata":{"annotations":{"drone-build":"${DRONE_BUILD_NUMBER}"}}}}}' \
          "$$KUBE_SERVER/apis/apps/v1/namespaces/health/deployments/health"
    environment:
      KUBE_TOKEN:
        from_secret: kube_token
      KUBE_SERVER:
        from_secret: kube_server

trigger:
  branch:
    - main
  event:
    - push
