when:
  - event: push
    branch: main

clone:
  git:
    image: alpine
    commands:
      - "apk update && apk add git"
      - "for i in 1 2 3 4 5; do git clone https://github.com/ViktorBarzin/health.git . && break || echo \"Clone attempt $i failed, retrying in 10s...\" && sleep 10; done"
      - "git checkout $CI_COMMIT_SHA"

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: viktorbarzin/health
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${CI_PIPELINE_NUMBER}

  - name: deploy
    image: curlimages/curl
    commands:
      - 'curl -s -X PATCH "https://10.0.20.100:6443/apis/apps/v1/namespaces/health/deployments/health" -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" -k -d ''[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"viktorbarzin/health:''"$CI_PIPELINE_NUMBER"''"}]'' | head'
